// <auto-generated />
using HarrysGroceryStore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HarrysGroceryStore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210417202934_update")]
    partial class update
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HarrysGroceryStore.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "john.doe@aol.com",
                            FirstName = "John",
                            LastName = "Doe",
                            PassWord = "John2020!",
                            PhoneNumber = "7134021336"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "michael.chan@gmail.com",
                            FirstName = "Michael",
                            LastName = "Chan",
                            PassWord = "Mike2020!",
                            PhoneNumber = "7135243201"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "claire4real@aol.com",
                            FirstName = "Clarie",
                            LastName = "Ramirez",
                            PassWord = "beauty",
                            PhoneNumber = "7134278974"
                        },
                        new
                        {
                            UserId = 4,
                            Email = "smithJohnson@outlook.com.com",
                            FirstName = "Smith",
                            LastName = "Johnson",
                            PassWord = "smitty1989!",
                            PhoneNumber = "2105412031"
                        },
                        new
                        {
                            UserId = 5,
                            Email = "voke.oluwafemi@aol.com",
                            FirstName = "Voke",
                            LastName = "Oluwafemi",
                            PassWord = "voke1900!",
                            PhoneNumber = "7138795214"
                        },
                        new
                        {
                            UserId = 6,
                            Email = "harryporter@aol.com",
                            FirstName = "Harry",
                            LastName = "Porter",
                            PassWord = "Porterisgood!",
                            PhoneNumber = "7137852140"
                        },
                        new
                        {
                            UserId = 7,
                            Email = "israelruiz@yahoo.com",
                            FirstName = "Israel",
                            LastName = "Ruiz",
                            PassWord = "Realsoccer!",
                            PhoneNumber = "7133020145"
                        },
                        new
                        {
                            UserId = 8,
                            Email = "austin.capstone@outlook.com",
                            FirstName = "Austin",
                            LastName = "Capstone",
                            PassWord = "capstone!",
                            PhoneNumber = "2103625479"
                        },
                        new
                        {
                            UserId = 9,
                            Email = "genesishoward@aol.com",
                            FirstName = "Genesis",
                            LastName = "Howard",
                            PassWord = "baller21!",
                            PhoneNumber = "2104021336"
                        },
                        new
                        {
                            UserId = 10,
                            Email = "christianwalcot@aol.com",
                            FirstName = "Christian",
                            LastName = "Walcot",
                            PassWord = "christian2005!",
                            PhoneNumber = "7134025241"
                        },
                        new
                        {
                            UserId = 11,
                            Email = "ngozi.Offodile@gmail.com",
                            FirstName = "Ngozi",
                            LastName = "Offodile",
                            PassWord = "ngozi2021!",
                            PhoneNumber = "7134042035"
                        },
                        new
                        {
                            UserId = 12,
                            Email = "adaobieze@yahoo.com",
                            FirstName = "Adaobi",
                            LastName = "Chukwueze",
                            PassWord = "ada2020!",
                            PhoneNumber = "2104021336"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
